# Hungarian translation for duplicity
# Copyright (c) 2011 Rosetta Contributors and Canonical Ltd 2011
# This file is distributed under the same license as the duplicity package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2011.
#
msgid ""
msgstr ""
"Project-Id-Version: duplicity\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2016-02-18 16:51+0000\n"
"PO-Revision-Date: 2015-01-10 15:43+0000\n"
"Last-Translator: Úr Balázs <urbalazs@gmail.com>\n"
"Language-Team: Hungarian <hu@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Launchpad-Export-Date: 2016-02-19 05:11+0000\n"
"X-Generator: Launchpad (build 17925)\n"

#: ../bin/duplicity:130
msgid "Reuse configured PASSPHRASE as SIGN_PASSPHRASE"
msgstr "A beállított PASSPHRASE újrafelhasználása mint SIGN_PASSPHRASE"

#: ../bin/duplicity:137
msgid "Reuse configured SIGN_PASSPHRASE as PASSPHRASE"
msgstr "A beállított SIGN_PASSPHRASE újrafelhasználása mint PASSPHRASE"

#: ../bin/duplicity:178
msgid "PASSPHRASE variable not set, asking user."
msgstr "PASSPHRASE változó nincs beállítva, elkérjük a felhasználótól."

#: ../bin/duplicity:193
msgid "GnuPG passphrase for signing key:"
msgstr "GnuPG jelszó a kulcs hitelesítéséhez:"

#: ../bin/duplicity:198
msgid "GnuPG passphrase:"
msgstr "GnuPG jelszó:"

#: ../bin/duplicity:203
msgid "Retype passphrase for signing key to confirm: "
msgstr "Megerősítésképpen írd be újra a jelszót a hitelesítéshez: "

#: ../bin/duplicity:205
msgid "Retype passphrase to confirm: "
msgstr "Megerősítésképpen írd be újra a jelszót: "

#: ../bin/duplicity:208
msgid "First and second passphrases do not match!  Please try again."
msgstr ""
"Az első és a második jelszó nem egyezik megy egymással! Próbáld újra."

#: ../bin/duplicity:213
msgid ""
"Cannot use empty passphrase with symmetric encryption!  Please try again."
msgstr "Szimmetrikus titkosításnál nem lehet üres a jelszó! Próbáld újra."

#: ../bin/duplicity:269
#, python-format
msgid ""
"File %s complete in backup set.\n"
"Continuing restart on file %s."
msgstr ""
"A %s állomány elkészült a biztonsági mentés készletben.\n"
"Folytatom ezzel a állománnyal: %s."

#: ../bin/duplicity:278
#, python-format
msgid ""
"File %s missing in backup set.\n"
"Continuing restart on file %s."
msgstr ""
"A %s állomány hiányzik a biztonsági mentés készletből.\n"
"Folytatom ezzel a állománnyal: %s."

#: ../bin/duplicity:327
#, python-format
msgid "File %s was corrupted during upload."
msgstr "%s állomány megsérült feltöltés közben."

#: ../bin/duplicity:360
msgid ""
"Restarting backup, but current encryption settings do not match original "
"settings"
msgstr ""
"Újraindítom a biztonsági mentést, de a jelenlegi titkosítási beállítások nem "
"azonosak azokkal amik eredetileg be voltak állítva."

#: ../bin/duplicity:383
#, python-format
msgid "Restarting after volume %s, file %s, block %s"
msgstr "Újraindítás %s kötet, %s fájl, %s blokk után"

#: ../bin/duplicity:451
#, python-format
msgid "Processed volume %d"
msgstr "%d kötet feldolgozva"

#: ../bin/duplicity:601
msgid ""
"Fatal Error: Unable to start incremental backup.  Old signatures not found "
"and incremental specified"
msgstr ""
"Súlyos hiba: Nem tudom elkezdeni a növekményes biztonsági mentést. Nem "
"találok régi aláírásokat, pedig növekményes mentést kezdeményeztél."

#: ../bin/duplicity:605
msgid "No signatures found, switching to full backup."
msgstr "Nem találtam aláírásokat, átváltok teljes biztonsági mentésre."

#: ../bin/duplicity:619
msgid "Backup Statistics"
msgstr "Biztonsági mentés statisztikák"

#: ../bin/duplicity:695
#, python-format
msgid "%s not found in archive, no files restored."
msgstr ""
"%s állományt nem találtam meg az archívban, nem állítottam vissza semmit."

#: ../bin/duplicity:728
msgid "No files found in archive - nothing restored."
msgstr "Nem találtam állományt az archívban - nem állítottam vissza semmit."

#: ../bin/duplicity:761
#, python-format
msgid "Processed volume %d of %d"
msgstr "%d köteg feldolgozva a %d-ból"

#: ../bin/duplicity:795
#, python-format
msgid "Invalid data - %s hash mismatch for file:"
msgstr "Érvénytelen adat - %s"

#: ../bin/duplicity:797
#, python-format
msgid "Calculated hash: %s"
msgstr "Számított hash: %s"

#: ../bin/duplicity:798
#, python-format
msgid "Manifest hash: %s"
msgstr "KImutatás hash: %s"

#: ../bin/duplicity:837
#, python-format
msgid "Volume was signed by key %s, not %s"
msgstr "A köteget %s kulccsal hitelesítették, nem %s kulccsal"

#: ../bin/duplicity:869
#, python-format
msgid "Verify complete: %s, %s."
msgstr "Ellenőrizve: %s, %s."

#: ../bin/duplicity:870
#, python-format
msgid "%d file compared"
msgid_plural "%d files compared"
msgstr[0] "%d file összehasonlítva"
msgstr[1] "%d file összehasonlítva"

#: ../bin/duplicity:872
#, python-format
msgid "%d difference found"
msgid_plural "%d differences found"
msgstr[0] "%d különbséget találtam"
msgstr[1] "%d különbséget találtam"

#: ../bin/duplicity:891
msgid "No extraneous files found, nothing deleted in cleanup."
msgstr ""
"Nem találtam extra állományt, nem töröltem semmit az adattiszítás során."

#: ../bin/duplicity:896
msgid "Deleting this file from backend:"
msgid_plural "Deleting these files from backend:"
msgstr[0] "A következő állomány törlése a tárhelyről:"
msgstr[1] "A következő állományok törlése a tárhelyről:"

#: ../bin/duplicity:908
msgid "Found the following file to delete:"
msgid_plural "Found the following files to delete:"
msgstr[0] "A következő törlendő állományt találtam:"
msgstr[1] "A következő törlendő állományokat találtam:"

#: ../bin/duplicity:912
msgid "Run duplicity again with the --force option to actually delete."
msgstr ""
"Indítsd el a duplicity-t újra a --force kapcsolóval, hogy valóban töröljek."

#: ../bin/duplicity:955
msgid "There are backup set(s) at time(s):"
msgstr ""
"A következő biztonsági mentés készlet(ek)et találtam a megadott "
"időpont(ok)ban:"

#: ../bin/duplicity:957
msgid "Which can't be deleted because newer sets depend on them."
msgstr "Amiket nem lehet törölni, mert újabb készletek függnek tőlük."

#: ../bin/duplicity:961
msgid ""
"Current active backup chain is older than specified time.  However, it will "
"not be deleted.  To remove all your backups, manually purge the repository."
msgstr ""
"Az aktuális biztonsági mentés lánc régebbi a megadott időpontnál. Ennek "
"ellenére nem törlöm ezeket. Az összes biztonsági mentést manuálisan töröld a "
"raktárból."

#: ../bin/duplicity:967
msgid "No old backup sets found, nothing deleted."
msgstr "Nem találtam régi biztonsági mentés készletet, nem töröltem semmit."

#: ../bin/duplicity:970
msgid "Deleting backup chain at time:"
msgid_plural "Deleting backup chains at times:"
msgstr[0] "Biztonsági mentés lánc törlése a következő időpontban:"
msgstr[1] "Biztonsági mentés láncok törlése a következő időpontokban:"

#: ../bin/duplicity:981
#, python-format
msgid "Deleting incremental signature chain %s"
msgstr "A(z) %s növekményes aláírás lánc törlése"

#: ../bin/duplicity:983
#, python-format
msgid "Deleting incremental backup chain %s"
msgstr "A(z) %s növekményes biztonsági mentés lánc törlése"

#: ../bin/duplicity:986
#, python-format
msgid "Deleting complete signature chain %s"
msgstr "A teljes %s aláírás lánc törlése"

#: ../bin/duplicity:988
#, python-format
msgid "Deleting complete backup chain %s"
msgstr "A teljes %s biztonsági mentés lánc törlése"

#: ../bin/duplicity:994
msgid "Found old backup chain at the following time:"
msgid_plural "Found old backup chains at the following times:"
msgstr[0] "Régi biztonsági mentés lánc található a következő időpontban:"
msgstr[1] ""
"Régi biztonsági mentés láncok találhatók a következő időpontokban:"

#: ../bin/duplicity:998
msgid "Rerun command with --force option to actually delete."
msgstr ""
"Futtasd le a parancsot újra a --force kapcsolóval, hogy valóban töröljem."

#: ../bin/duplicity:1075
#, python-format
msgid "Deleting local %s (not authoritative at backend)."
msgstr "Helyi %s törlése (nem hiteles a tárhelyen)."

#: ../bin/duplicity:1079
#, python-format
msgid "Unable to delete %s: %s"
msgstr "Nem tudtam törölni: %s: %s"

#: ../bin/duplicity:1109 ../duplicity/dup_temp.py:265
#, python-format
msgid "Failed to read %s: %s"
msgstr "Nem tudtam beolvasni: %s: %s"

#: ../bin/duplicity:1123
#, python-format
msgid "Copying %s to local cache."
msgstr "%s másolása a helyi gyorsítótárba."

#: ../bin/duplicity:1171
msgid "Local and Remote metadata are synchronized, no sync needed."
msgstr ""
"Helyi és távoli metaadatok szinkronban vannak, nem kell szinkronizálni."

#: ../bin/duplicity:1176
msgid "Synchronizing remote metadata to local cache..."
msgstr "Távoli metaadatok letöltése a helyi gyorsítótárba..."

#: ../bin/duplicity:1191
msgid "Sync would copy the following from remote to local:"
msgstr "A következőt nem tudtam letölteni a helyi gyorsítótárba:"

#: ../bin/duplicity:1194
msgid "Sync would remove the following spurious local files:"
msgstr ""
"Szinkronizálás során le kell törölni a következő hamis helyi állományokat:"

#: ../bin/duplicity:1237
msgid "Unable to get free space on temp."
msgstr "Nincs már szabad hely az átmeneti (temp) tárolóban."

#: ../bin/duplicity:1245
#, python-format
msgid "Temp space has %d available, backup needs approx %d."
msgstr ""
"Az átmeneti (temp) tárolóban %d hely van, a biztonsági mentéshez kb. %d "
"kellene."

#: ../bin/duplicity:1248
#, python-format
msgid "Temp has %d available, backup will use approx %d."
msgstr ""
"Az átmeneti (temp) tárolóban %d hely van, a biztonsági mentéshez kb. %d "
"kellene."

#: ../bin/duplicity:1256
msgid "Unable to get max open files."
msgstr "Nem sikerült lekérdezni, hogy hány állomány nyitható meg egy időben."

#: ../bin/duplicity:1260
#, python-format
msgid ""
"Max open files of %s is too low, should be >= 1024.\n"
"Use 'ulimit -n 1024' or higher to correct.\n"
msgstr ""
"Egyszerre csak %s állomány nyitható meg a rendszerben, ez kevés, legalább "
">=1024 kellene.\n"
"A megoldás: 'ulimit -n 1024' (vagy még magasabb érték).\n"

#: ../bin/duplicity:1311
msgid ""
"RESTART: The first volume failed to upload before termination.\n"
"         Restart is impossible...starting backup from beginning."
msgstr ""
"ÚJRAKEZDÉS: Az első köteget nem sikerült feltölteni a tárhelyre.\n"
"            Nem tudom helyreállítani... biztonsági mentés újraindítása."

#: ../bin/duplicity:1317
#, python-format
msgid ""
"RESTART: Volumes %d to %d failed to upload before termination.\n"
"         Restarting backup at volume %d."
msgstr ""
"ÚJRAKEZDÉS: Az %d - %d köteget nem sikerült feltölteni a tárhelyre.\n"
"            Biztonsági mentés újraindítása a %d. kötegnél."

#: ../bin/duplicity:1324
#, python-format
msgid ""
"RESTART: Impossible backup state: manifest has %d vols, remote has %d vols.\n"
"         Restart is impossible ... duplicity will clean off the last "
"partial\n"
"         backup then restart the backup from the beginning."
msgstr ""
"ÚJRAKEZDÉS: Lehetetlen állapot: a bizonylatok szerint %d kötegünk van, a "
"tárhelyen %d.\n"
"            Újraindítani sem lehet... törlöm a legutolső sérült mentés "
"kötegeit,\n"
"            majd újraindítom a biztonsági mentést."

#: ../bin/duplicity:1345
msgid ""
"\n"
"PYTHONOPTIMIZE in the environment causes duplicity to fail to\n"
"recognize its own backups.  Please remove PYTHONOPTIMIZE from\n"
"the environment and rerun the backup.\n"
"\n"
"See https://bugs.launchpad.net/duplicity/+bug/931175\n"
msgstr ""

#: ../bin/duplicity:1330
msgid ""
"\n"
"Duplicity 0.6 series is being deprecated:\n"
"See http://www.nongnu.org/duplicity/\n"
msgstr ""

#: ../bin/duplicity:1428
#, python-format
msgid "Last %s backup left a partial set, restarting."
msgstr ""
"Az utolsó %s biztonsági mentés hiányos készletet hagyott maga után, "
"újraindítás."

#: ../bin/duplicity:1432
#, python-format
msgid "Cleaning up previous partial %s backup set, restarting."
msgstr "Előző %s hiányos biztonsági mentés tisztítása, újraindítás."

#: ../bin/duplicity:1443
msgid "Last full backup date:"
msgstr "Utolsó teljes biztonsági mentés dátuma:"

#: ../bin/duplicity:1445
msgid "Last full backup date: none"
msgstr "Legutolsó teljes biztonsági mentés dátuma: nincs."

#: ../bin/duplicity:1447
msgid "Last full backup is too old, forcing full backup"
msgstr "Legutolsó teljes biztonsági mentés túl régi, teljes mentés kell."

#: ../bin/duplicity:1493
msgid ""
"When using symmetric encryption, the signing passphrase must equal the "
"encryption passphrase."
msgstr ""
"Szimmetrikus titkosítás használatakor az aláíró jelszónak meg kell egyeznie "
"a titkosítási jelszóval."

#: ../bin/duplicity:1546
msgid "INT intercepted...exiting."
msgstr "INT jelzés érkezett... kilépés."

#: ../bin/duplicity:1554
#, python-format
msgid "GPG error detail: %s"
msgstr "GPG hiba részletei: %s"

#: ../bin/duplicity:1564
#, python-format
msgid "User error detail: %s"
msgstr "Felhasználói hiba: %s"

#: ../bin/duplicity:1574
#, python-format
msgid "Backend error detail: %s"
msgstr "Tárhely hiba részletei: %s"

#: ../bin/rdiffdir:61 ../duplicity/commandline.py:259
#, python-format
msgid "Error opening file %s"
msgstr "Hiba a %s állomány megnyitása közben"

#: ../bin/rdiffdir:128
#, python-format
msgid "File %s already exists, will not overwrite."
msgstr "A(z) %s fájl már létezik, nem lesz felülírva."

#: ../duplicity/selection.py:127
#, python-format
msgid "Skipping socket %s"
msgstr "Konnektor (socket) átugrása: %s"

#: ../duplicity/selection.py:131
#, python-format
msgid "Error initializing file %s"
msgstr "Hiba történt a %s állomány inicializálása során"

#: ../duplicity/selection.py:135 ../duplicity/selection.py:157
#, python-format
msgid "Error accessing possibly locked file %s"
msgstr "Valószínűleg zárolt a %s állomány, nem érem el"

#: ../duplicity/selection.py:172
#, python-format
msgid "Warning: base %s doesn't exist, continuing"
msgstr "Figyelem: %s alap nem létezik, folytatom"

#: ../duplicity/selection.py:175 ../duplicity/selection.py:193
#: ../duplicity/selection.py:196
#, python-format
msgid "Selecting %s"
msgstr "%s kiválasztása"

#: ../duplicity/selection.py:293
#, python-format
msgid ""
"Fatal Error: The file specification\n"
"    %s\n"
"cannot match any files in the base directory\n"
"    %s\n"
"Useful file specifications begin with the base directory or some\n"
"pattern (such as '**') which matches the base directory."
msgstr ""
"Súlyos hiba: Az állomány specifikáció\n"
"    %s\n"
"nem illik az alapkönyvtárban található állományokra\n"
"    %s\n"
"Egy állományspecifikáció az alapkönyvtárral kezdődjön, vagy\n"
"valamilyen minta (mint pl. a '**') illeszkedjen az alapkönyvtárra."

#: ../duplicity/selection.py:302
#, python-format
msgid ""
"Fatal Error while processing expression\n"
"%s"
msgstr ""
"Súlyos hiba: A kifejezés feldolgozása során hiba történt:\n"
"%s"

#: ../duplicity/selection.py:312
#, python-format
msgid ""
"Last selection expression:\n"
"    %s\n"
"only specifies that files be included.  Because the default is to\n"
"include all files, the expression is redundant.  Exiting because this\n"
"probably isn't what you meant."
msgstr ""
"Legutolsó kiválasztó kifejezés:\n"
"    %s\n"
"csak azt fejezi ki, hogy állományokat foglaljunk be. \n"
"Mivel az alapértelmezés szerint minden állományt befoglalunk,\n"
"a kifejezés felesleges. Kilépek, mert valószínűleg nem ezt akartad."

#: ../duplicity/selection.py:311
#, python-format
msgid "Reading filelist %s"
msgstr "%s állománylista beolvasása"

#: ../duplicity/selection.py:314
#, python-format
msgid "Sorting filelist %s"
msgstr "%s állománylista sorbarendezése"

#: ../duplicity/selection.py:341
#, python-format
msgid ""
"Warning: file specification '%s' in filelist %s\n"
"doesn't start with correct prefix %s.  Ignoring."
msgstr ""
"Figyelem: a '%s' állományspecifikáció a %s állománylistában\n"
"nem a helyes %s előtaggal kezdődik. Kihagyom."

#: ../duplicity/selection.py:345
msgid "Future prefix errors will not be logged."
msgstr "A további előtag hibákat nem jegyzem le."

#: ../duplicity/selection.py:361
#, python-format
msgid "Error closing filelist %s"
msgstr "Hiba történt a %s állománylista lezárása során"

#: ../duplicity/selection.py:368
#, python-format
msgid "Reading globbing filelist %s"
msgstr "Globbing állománylista %s beolvasása"

#: ../duplicity/selection.py:401
#, python-format
msgid "Error compiling regular expression %s"
msgstr "Hiba történt a %s reguláris kifejezés lefordítása során"

#: ../duplicity/selection.py:418
msgid ""
"Warning: exclude-device-files is not the first selector.\n"
"This may not be what you intended"
msgstr ""
"Figyelem: az exclude-device-files nem az első kiválasztó.\n"
"Valószínűleg nem ezt akarod"

#: ../duplicity/commandline.py:71
#, python-format
msgid ""
"Warning: Option %s is pending deprecation and will be removed in a future "
"release.\n"
"Use of default filenames is strongly suggested."
msgstr ""
"Figyelem: a %s opció már elavult, és későbbi verziókban meg is fog szűnni.\n"
"Alapértelmezett állománynevek használata erősen javasolt."

#: ../duplicity/commandline.py:216
#, python-format
msgid "Unable to load gio backend: %s"
msgstr ""

#. Used in usage help to represent a Unix-style path name. Example:
#. --archive-dir <path>
#: ../duplicity/commandline.py:280 ../duplicity/commandline.py:290
#: ../duplicity/commandline.py:307 ../duplicity/commandline.py:381
#: ../duplicity/commandline.py:399 ../duplicity/commandline.py:591
#: ../duplicity/commandline.py:624 ../duplicity/commandline.py:810
msgid "path"
msgstr "útvonal"

#. Used in usage help to represent an ID for a GnuPG key. Example:
#. --encrypt-key <gpg_key_id>
#. Used in usage help to represent an ID for a hidden GnuPG key. Example:
#. --hidden-encrypt-key <gpg_key_id>
#. Used in usage help to represent an ID for a GnuPG key. Example:
#. --encrypt-key <gpg_key_id>
#: ../duplicity/commandline.py:302 ../duplicity/commandline.py:309
#: ../duplicity/commandline.py:405 ../duplicity/commandline.py:575
#: ../duplicity/commandline.py:783
msgid "gpg-key-id"
msgstr "gpg-kulcs-azon"

#. Used in usage help to represent a "glob" style pattern for
#. matching one or more files, as described in the documentation.
#. Example:
#. --exclude <shell_pattern>
#: ../duplicity/commandline.py:317 ../duplicity/commandline.py:430
#: ../duplicity/commandline.py:833
msgid "shell_pattern"
msgstr "héj_minta"

#. Used in usage help to represent the name of a file. Example:
#. --log-file <filename>
#: ../duplicity/commandline.py:323 ../duplicity/commandline.py:332
#: ../duplicity/commandline.py:339 ../duplicity/commandline.py:432
#: ../duplicity/commandline.py:439 ../duplicity/commandline.py:452
#: ../duplicity/commandline.py:779
msgid "filename"
msgstr "állománynév"

#. Used in usage help to represent a regular expression (regexp).
#: ../duplicity/commandline.py:346 ../duplicity/commandline.py:443
msgid "regular_expression"
msgstr "reguláris_kifejezés"

#. Used in usage help to represent a time spec for a previous
#. point in time, as described in the documentation. Example:
#. duplicity remove-older-than time [options] target_url
#: ../duplicity/commandline.py:350 ../duplicity/commandline.py:393
#: ../duplicity/commandline.py:514 ../duplicity/commandline.py:865
msgid "time"
msgstr "időpont"

#. Used in usage help. (Should be consistent with the "Options:"
#. header.) Example:
#. duplicity [full|incremental] [options] source_dir target_url
#: ../duplicity/commandline.py:401 ../duplicity/commandline.py:494
#: ../duplicity/commandline.py:517 ../duplicity/commandline.py:583
#: ../duplicity/commandline.py:798
msgid "options"
msgstr "opciók"

#: ../duplicity/commandline.py:416
#, python-format
msgid ""
"Running in 'ignore errors' mode due to %s; please re-consider if this was "
"not intended"
msgstr ""
"'Hibák figyelmen kívül hagyása' módban vagyunk, emiatt: %s; kérlek gondold "
"át, ez volt-e a szándékod"

#. Used in usage help to represent an imap mailbox
#: ../duplicity/commandline.py:428
msgid "imap_mailbox"
msgstr "imap_postaláda"

#: ../duplicity/commandline.py:446
msgid "file_descriptor"
msgstr "állomány_leíró"

#. Used in usage help to represent a desired number of
#. something. Example:
#. --num-retries <number>
#: ../duplicity/commandline.py:457 ../duplicity/commandline.py:479
#: ../duplicity/commandline.py:491 ../duplicity/commandline.py:500
#: ../duplicity/commandline.py:541 ../duplicity/commandline.py:546
#: ../duplicity/commandline.py:550 ../duplicity/commandline.py:619
#: ../duplicity/commandline.py:793
msgid "number"
msgstr "szám"

#. Used in usage help (noun)
#: ../duplicity/commandline.py:460
msgid "backup name"
msgstr "biztonsági mentés neve"

#. noun
#: ../duplicity/commandline.py:559 ../duplicity/commandline.py:562
#: ../duplicity/commandline.py:764
msgid "command"
msgstr "parancs"

#: ../duplicity/commandline.py:565
msgid "pyrax|cloudfiles"
msgstr ""

#: ../duplicity/commandline.py:546
msgid "paramiko|pexpect"
msgstr ""

#: ../duplicity/commandline.py:586
msgid "pem formatted bundle of certificate authorities"
msgstr ""

#. Used in usage help. Example:
#. --timeout <seconds>
#: ../duplicity/commandline.py:596 ../duplicity/commandline.py:827
msgid "seconds"
msgstr "másodpercek"

#. abbreviation for "character" (noun)
#: ../duplicity/commandline.py:602 ../duplicity/commandline.py:761
msgid "char"
msgstr "kar"

#: ../duplicity/commandline.py:727
#, python-format
msgid "Using archive dir: %s"
msgstr "Archívum-könyvtár: %s"

#: ../duplicity/commandline.py:728
#, python-format
msgid "Using backup name: %s"
msgstr "Biztonsági mentés neve: %s"

#: ../duplicity/commandline.py:735
#, python-format
msgid "Command line error: %s"
msgstr "Parancssori hiba: %s"

#: ../duplicity/commandline.py:736
msgid "Enter 'duplicity --help' for help screen."
msgstr "A súgó megjeleníthető a következő parancssal: 'duplicity --help'."

#. Used in usage help to represent a Unix-style path name. Example:
#. rsync://user[:password]@other_host[:port]//absolute_path
#: ../duplicity/commandline.py:749
msgid "absolute_path"
msgstr "teljes_útvonal"

#. Used in usage help. Example:
#. tahoe://alias/some_dir
#: ../duplicity/commandline.py:753
msgid "alias"
msgstr "alias"

#. Used in help to represent a "bucket name" for Amazon Web
#. Services' Simple Storage Service (S3). Example:
#. s3://other.host/bucket_name[/prefix]
#: ../duplicity/commandline.py:758
msgid "bucket_name"
msgstr "bucket_name"

#. Used in usage help to represent the name of a container in
#. Amazon Web Services' Cloudfront. Example:
#. cf+http://container_name
#: ../duplicity/commandline.py:769
msgid "container_name"
msgstr "container_name"

#. noun
#: ../duplicity/commandline.py:772
msgid "count"
msgstr "száma"

#. Used in usage help to represent the name of a file directory
#: ../duplicity/commandline.py:775
msgid "directory"
msgstr "könyvtár"

#. Used in usage help, e.g. to represent the name of a code
#. module. Example:
#. rsync://user[:password]@other.host[:port]::/module/some_dir
#: ../duplicity/commandline.py:788
msgid "module"
msgstr "modul"

#. Used in usage help to represent an internet hostname. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/commandline.py:802
msgid "other.host"
msgstr "egyéb.kiszolgáló"

#. Used in usage help. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/commandline.py:806
msgid "password"
msgstr "jelszó"

#. Used in usage help to represent a TCP port number. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/commandline.py:814
msgid "port"
msgstr "port"

#. Used in usage help. This represents a string to be used as a
#. prefix to names for backup files created by Duplicity. Example:
#. s3://other.host/bucket_name[/prefix]
#: ../duplicity/commandline.py:819
msgid "prefix"
msgstr "prefix"

#. Used in usage help to represent a Unix-style path name. Example:
#. rsync://user[:password]@other.host[:port]/relative_path
#: ../duplicity/commandline.py:823
msgid "relative_path"
msgstr "relatív_útvonal"

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory. Example:
#. file:///some_dir
#: ../duplicity/commandline.py:838
msgid "some_dir"
msgstr "valami_könyvtár"

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory where files will be
#. coming FROM. Example:
#. duplicity [full|incremental] [options] source_dir target_url
#: ../duplicity/commandline.py:844
msgid "source_dir"
msgstr "forrás_könyvtár"

#. Used in usage help to represent a URL files will be coming
#. FROM. Example:
#. duplicity [restore] [options] source_url target_dir
#: ../duplicity/commandline.py:849
msgid "source_url"
msgstr "forrás_url"

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory. where files will be
#. going TO. Example:
#. duplicity [restore] [options] source_url target_dir
#: ../duplicity/commandline.py:855
msgid "target_dir"
msgstr "cél_könyvtár"

#. Used in usage help to represent a URL files will be going TO.
#. Example:
#. duplicity [full|incremental] [options] source_dir target_url
#: ../duplicity/commandline.py:860
msgid "target_url"
msgstr "cél_url"

#. Used in usage help to represent a user name (i.e. login).
#. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/commandline.py:870
msgid "user"
msgstr "felhasználó"

#. Header in usage help
#: ../duplicity/commandline.py:895
msgid "Backends and their URL formats:"
msgstr "Tárhelyek és azok URL formátumai:"

#. Header in usage help
#: ../duplicity/commandline.py:925
msgid "Commands:"
msgstr "Parancsok:"

#: ../duplicity/commandline.py:949
#, python-format
msgid ""
"Specified archive directory '%s' does not exist, or is not a directory"
msgstr "A megadott '%s' archív könyvtár nem létezik, vagy nem könyvtár"

#: ../duplicity/commandline.py:908
#, python-format
msgid ""
"Sign key should be an 8 character hex string, like 'AA0E73D2'.\n"
"Received '%s' instead."
msgstr ""
"Az aláíró kulcs egy 8 karakter hosszú hex szöveg, pl. 'AA0E73D2'.\n"
"Ehelyett ezt kaptam: '%s'."

#: ../duplicity/commandline.py:1018
#, python-format
msgid ""
"Restore destination directory %s already exists.\n"
"Will not overwrite."
msgstr ""
"A visszaállításhoz kért %s könyvár már létezik.\n"
"Nem írom felül."

#: ../duplicity/commandline.py:1023
#, python-format
msgid "Verify directory %s does not exist"
msgstr "Az ellenőrzéshez kért %s könyvtár nem létezik"

#: ../duplicity/commandline.py:1029
#, python-format
msgid "Backup source directory %s does not exist."
msgstr "Biztonsági mentés %s forráskönyvtár nem létezik."

#: ../duplicity/commandline.py:1060
#, python-format
msgid "Command line warning: %s"
msgstr "Parancssori figyelmetetés: %s"

#: ../duplicity/commandline.py:1060
msgid ""
"Selection options --exclude/--include\n"
"currently work only when backing up,not restoring."
msgstr ""
"Az --exclude/--include állományválasztó opciók jelenleg csak \n"
"biztonsági mentéshez használhatók, visszaállításhoz nem."

#: ../duplicity/commandline.py:1110
#, python-format
msgid ""
"Bad URL '%s'.\n"
"Examples of URL strings are \"scp://user@host.net:1234/path\" and\n"
"\"file:///usr/local\".  See the man page for more information."
msgstr ""
"Rossz URL '%s'.\n"
"Néhány példa-URL: \"scp://user@host.net:1234/path\" vagy\n"
"\"file:///usr/local\". Olvass utána a \"man\" oldalon."

#: ../duplicity/commandline.py:1135
msgid "Main action: "
msgstr "Fő művelet: "

#: ../duplicity/backend.py:102
#, python-format
msgid "Import of %s %s"
msgstr "%s %s importálása"

#: ../duplicity/backend.py:211
#, python-format
msgid "Could not initialize backend: %s"
msgstr "Nem sikerült előkészíteni a háttérprogramot: %s"

#: ../duplicity/backend.py:321
#, python-format
msgid "Attempt %s failed: %s: %s"
msgstr ""

#: ../duplicity/backend.py:371
#, python-format
msgid "Backtrace of previous error: %s"
msgstr ""

#: ../duplicity/backend.py:390
#, python-format
msgid "Attempt %s failed. %s: %s"
msgstr "%s próbálkozása meghiúsult. %s: %s"

#: ../duplicity/backend.py:386
#, python-format
msgid "Giving up after %s attempts. %s: %s"
msgstr "Feladtam %s próbálkozás után. %s: %s"

#: ../duplicity/backend.py:476
#, python-format
msgid "Reading results of '%s'"
msgstr "'%s' eredményeinek beolvasása"

#: ../duplicity/backend.py:586
#, python-format
msgid "Running '%s' failed with code %d (attempt #%d)"
msgid_plural "Running '%s' failed with code %d (attempt #%d)"
msgstr[0] "'%s' futtatása sikertelen volt, kód: %d ( #%d. próbálkozás)"
msgstr[1] "'%s' futtatása sikertelen volt, kód: %d ( #%d. próbálkozás)"

#: ../duplicity/backend.py:590
#, python-format
msgid ""
"Error is:\n"
"%s"
msgstr ""
"A hiba:\n"
"%s"

#: ../duplicity/backend.py:592
#, python-format
msgid "Giving up trying to execute '%s' after %d attempt"
msgid_plural "Giving up trying to execute '%s' after %d attempts"
msgstr[0] "Feladtam a(z) „%s” végrehajtásának kísérletét %d próbálkozás után"
msgstr[1] "Feladtam a(z) „%s” végrehajtásának kísérletét %d próbálkozás után"

#: ../duplicity/asyncscheduler.py:67
#, python-format
msgid "instantiating at concurrency %d"
msgstr "Példányosítás, %d konkurencia szinten"

#: ../duplicity/asyncscheduler.py:94
msgid "inserting barrier"
msgstr "korlát beillesztése"

#: ../duplicity/asyncscheduler.py:143
msgid "running task synchronously (asynchronicity disabled)"
msgstr "feladatok szinkronizált futtatása (aszinkron letiltva)"

#: ../duplicity/asyncscheduler.py:149
msgid "scheduling task for asynchronous execution"
msgstr "feladatok ütemezése aszinkron futtatáshoz"

#: ../duplicity/asyncscheduler.py:178
msgid "task completed successfully"
msgstr "sikeres feladatvégrehajtás"

#: ../duplicity/asyncscheduler.py:189
msgid ""
"a previously scheduled task has failed; propagating the result immediately"
msgstr "egy előző ütemezett feladat hibára futott; az eredmény közlése indul"

#: ../duplicity/asyncscheduler.py:212 ../duplicity/asyncscheduler.py:233
#, python-format
msgid "active workers = %d"
msgstr "aktív munkások = %d"

#: ../duplicity/asyncscheduler.py:253
#, python-format
msgid "task execution done (success: %s)"
msgstr "feladat végrehajtva (siker: %s)"

#: ../duplicity/patchdir.py:80 ../duplicity/patchdir.py:85
#, python-format
msgid "Patching %s"
msgstr "%s foltozása (patch)"

#: ../duplicity/patchdir.py:532
#, python-format
msgid "Error '%s' patching %s"
msgstr ""

#: ../duplicity/patchdir.py:607
#, python-format
msgid "Writing %s of type %s"
msgstr "%s írása, mely %s típusú"

#: ../duplicity/collections.py:161 ../duplicity/collections.py:172
#, python-format
msgid "BackupSet.delete: missing %s"
msgstr ""

#: ../duplicity/collections.py:197
msgid "Fatal Error: No manifests found for most recent backup"
msgstr ""
"Súlyos hiba: A legutóbbi biztonsági mentéshez nem találtam bizonylatot"

#: ../duplicity/collections.py:206
msgid ""
"Fatal Error: Remote manifest does not match local one.  Either the remote "
"backup set or the local archive directory has been corrupted."
msgstr "Súlyos hiba:"

#: ../duplicity/collections.py:214
msgid "Fatal Error: Neither remote nor local manifest is readable."
msgstr "Súlyos hiba: Sem a helyi, sem a távoli kimutatás nem olvasható."

#: ../duplicity/collections.py:327
msgid "Preferring Backupset over previous one!"
msgstr "Mentés-készlet előnyben részesítve az előzővel szemben!"

#: ../duplicity/collections.py:330
#, python-format
msgid "Ignoring incremental Backupset (start_time: %s; needed: %s)"
msgstr ""
"Növekményes készlet figyelmen kívül hagyása (kezdésidő: %s; ez kellene: %s)"

#: ../duplicity/collections.py:335
#, python-format
msgid "Added incremental Backupset (start_time: %s / end_time: %s)"
msgstr "Növekményes biztonsági mentés hozzáadva (kezdésidő: %s; vége: %s)"

#: ../duplicity/collections.py:405
msgid "Chain start time: "
msgstr "Lánc kezdődiő: "

#: ../duplicity/collections.py:406
msgid "Chain end time: "
msgstr "Lánc vége: "

#: ../duplicity/collections.py:407
#, python-format
msgid "Number of contained backup sets: %d"
msgstr "Tartalmazott biztonsági mentés készletek száma: %d"

#: ../duplicity/collections.py:409
#, python-format
msgid "Total number of contained volumes: %d"
msgstr "Összes tartalmazott köteg száma: %d"

#: ../duplicity/collections.py:411 ../duplicity/collections.py:1198
msgid "Type of backup set:"
msgstr "Biztonsági mentés készlet típusa:"

#: ../duplicity/collections.py:411 ../duplicity/collections.py:1198
msgid "Time:"
msgstr "Idő:"

#: ../duplicity/collections.py:411
msgid "Num volumes:"
msgstr "Kötegek száma:"

#: ../duplicity/collections.py:415 ../duplicity/collections.py:1204
msgid "Full"
msgstr "Teljes"

#: ../duplicity/collections.py:418 ../duplicity/collections.py:1206
msgid "Incremental"
msgstr "Növekményes"

#: ../duplicity/collections.py:478
msgid "local"
msgstr "helyi"

#: ../duplicity/collections.py:480
msgid "remote"
msgstr "távoli"

#: ../duplicity/collections.py:635
msgid "Collection Status"
msgstr "Gyűjtemény állapota"

#: ../duplicity/collections.py:637
#, python-format
msgid "Connecting with backend: %s"
msgstr "Kapcsolódás a tárhelyhez: %s"

#: ../duplicity/collections.py:639
#, python-format
msgid "Archive dir: %s"
msgstr "Archívum könyvtár: %s"

#: ../duplicity/collections.py:642
#, python-format
msgid "Found %d secondary backup chain."
msgid_plural "Found %d secondary backup chains."
msgstr[0] "%d másodlagos mentés-láncot találtam"
msgstr[1] "%d másodlagos mentés-láncot találtam"

#: ../duplicity/collections.py:647
#, python-format
msgid "Secondary chain %d of %d:"
msgstr "Mentés-lánc %d, összesen %d"

#: ../duplicity/collections.py:653
msgid "Found primary backup chain with matching signature chain:"
msgstr "Találtam elsődleges mentés-láncot amire illik az aláíráslánc:"

#: ../duplicity/collections.py:657
msgid "No backup chains with active signatures found"
msgstr "Nem találtam mentés-láncot aminek aktív aláírása lenne"

#: ../duplicity/collections.py:660
#, python-format
msgid "Also found %d backup set not part of any chain,"
msgid_plural "Also found %d backup sets not part of any chain,"
msgstr[0] "Találtam még %d mentés-készletet, ami nem része láncnak."
msgstr[1] "Találtam még %d mentés-készletet, ami nem része láncnak."

#: ../duplicity/collections.py:664
#, python-format
msgid "and %d incomplete backup set."
msgid_plural "and %d incomplete backup sets."
msgstr[0] "és %d félkész mentés-készlet."
msgstr[1] "és %d félkész mentés-készlet."

#. "cleanup" is a hard-coded command, so do not translate it
#: ../duplicity/collections.py:669
msgid ""
"These may be deleted by running duplicity with the \"cleanup\" command."
msgstr "Ezeket le lehet törölni a duplicity \"cleanup\" parancsával."

#: ../duplicity/collections.py:672
msgid "No orphaned or incomplete backup sets found."
msgstr "Nem találtam elárvult vagy félkész biztonsági mentés készletet."

#: ../duplicity/collections.py:688
#, python-format
msgid "%d file exists on backend"
msgid_plural "%d files exist on backend"
msgstr[0] "%d állomány található a tárhelyen"
msgstr[1] "%d állomány található a tárhelyen"

#: ../duplicity/collections.py:695
#, python-format
msgid "%d file exists in cache"
msgid_plural "%d files exist in cache"
msgstr[0] "%d állomány található a gyorsítótárban"
msgstr[1] "%d állomány található a gyorsítótárban"

#: ../duplicity/collections.py:747
msgid ""
"Warning, discarding last backup set, because of missing signature file."
msgstr ""
"Figyelem, törlöm az utolsó mentés készletet, mert hiányzik az aláírás-"
"állomány."

#: ../duplicity/collections.py:770
msgid "Warning, found the following local orphaned signature file:"
msgid_plural "Warning, found the following local orphaned signature files:"
msgstr[0] "Figyelem, az alábbi elárvult aláírás-állományt találtam:"
msgstr[1] "Figyelem, az alábbi elárvult aláírás-állományokat találtam:"

#: ../duplicity/collections.py:779
msgid "Warning, found the following remote orphaned signature file:"
msgid_plural "Warning, found the following remote orphaned signature files:"
msgstr[0] ""
"Figyelem, az alábbi elárvult aláírás-állományt találtam a tárhelyen:"
msgstr[1] ""
"Figyelem, az alábbi elárvult aláírás-állományokat találtam a tárhelyen:"

#: ../duplicity/collections.py:788
msgid "Warning, found signatures but no corresponding backup files"
msgstr ""
"Figyelem, találtam aláírásokat, de nincs hozzátartozó mentés állomány"

#: ../duplicity/collections.py:792
msgid ""
"Warning, found incomplete backup sets, probably left from aborted session"
msgstr ""
"Figyelem, találtam félkész mentés készleteket, valószínűleg egy előző mentés "
"félbeszakadt"

#: ../duplicity/collections.py:796
msgid "Warning, found the following orphaned backup file:"
msgid_plural "Warning, found the following orphaned backup files:"
msgstr[0] "Figyelem, az alábbi elárvult mentés állományt találtam:"
msgstr[1] "Figyelem, az alábbi elárvult mentés állományokat találtam:"

#: ../duplicity/collections.py:813
#, python-format
msgid "Extracting backup chains from list of files: %s"
msgstr "Biztonsági mentés láncok kiemelése állománylistából: %s"

#: ../duplicity/collections.py:824
#, python-format
msgid "File %s is part of known set"
msgstr "A %s állomány nem része bármely ismert készletnek"

#: ../duplicity/collections.py:827
#, python-format
msgid "File %s is not part of a known set; creating new set"
msgstr ""
"A %s állomány nem része bármely ismert készletnek; új készlet létrehozása"

#: ../duplicity/collections.py:832
#, python-format
msgid "Ignoring file (rejected by backup set) '%s'"
msgstr "Állomány kihagyása (mentés készlet utasította el) '%s'"

#: ../duplicity/collections.py:848
#, python-format
msgid "Found backup chain %s"
msgstr "Megvan a biztonsági mentés lánc: %s"

#: ../duplicity/collections.py:853
#, python-format
msgid "Added set %s to pre-existing chain %s"
msgstr "%s készletet hozzáadtam a már létező %s lánchoz"

#: ../duplicity/collections.py:857
#, python-format
msgid "Found orphaned set %s"
msgstr "Elárvult %s készletet találtam"

#: ../duplicity/collections.py:1008
#, python-format
msgid ""
"No signature chain for the requested time.  Using oldest available chain, "
"starting at time %s."
msgstr ""
"Nincs aláíráslánc a kért időpontban. A legrégebbi láncot veszem elő, "
"időpontja %s."

#: ../duplicity/robust.py:61
#, python-format
msgid "Error listing directory %s"
msgstr "Hiba történt a %s könyvtár listázása során"

#: ../duplicity/diffdir.py:108 ../duplicity/diffdir.py:398
#, python-format
msgid "Error %s getting delta for %s"
msgstr "%s hiba a %s különbségi állományának kinyerése közben"

#: ../duplicity/diffdir.py:122
#, python-format
msgid "Getting delta of %s and %s"
msgstr "%s és %s különbségi állományának kinyerése"

#: ../duplicity/diffdir.py:167
#, python-format
msgid "A %s"
msgstr "+ %s"

#: ../duplicity/diffdir.py:174
#, python-format
msgid "M %s"
msgstr "* %s"

#: ../duplicity/diffdir.py:196
#, python-format
msgid "Comparing %s and %s"
msgstr "%s és %s összehasonlítása"

#: ../duplicity/diffdir.py:204
#, python-format
msgid "D %s"
msgstr "- %s"

#: ../duplicity/lazy.py:334
#, python-format
msgid "Warning: oldindex %s >= newindex %s"
msgstr "Figyelem: régi index %s >= új index %s"

#: ../duplicity/lazy.py:409
#, python-format
msgid "Error '%s' processing %s"
msgstr "'%s' hiba a %s feldolgozása közben"

#: ../duplicity/lazy.py:419
#, python-format
msgid "Skipping %s because of previous error"
msgstr "%s átugrása az előző hiba miatt"

#: ../duplicity/backends/sshbackend.py:25
#, python-format
msgid ""
"Warning: Option %s is supported by ssh pexpect backend only and will be "
"ignored."
msgstr ""

#: ../duplicity/backends/sshbackend.py:33
#, python-format
msgid ""
"Warning: Selected ssh backend '%s' is neither 'paramiko nor 'pexpect'. Will "
"use default paramiko instead."
msgstr ""

#: ../duplicity/backends/giobackend.py:108
#, python-format
msgid "Connection failed, please check your password: %s"
msgstr "Kapcsolódás sikertelen, kérlek ellenőrizd a jelszót: %s"

#: ../duplicity/backend.py:525
#, python-format
msgid "Writing %s"
msgstr "%s írása"

#: ../duplicity/manifest.py:91
#, python-format
msgid ""
"Fatal Error: Backup source host has changed.\n"
"Current hostname: %s\n"
"Previous hostname: %s"
msgstr ""
"Súlyos hiba: A biztonsági mentést kérő forrásrendszer neve megváltozott.\n"
"Jelenlegi név: %s\n"
"Előző név: %s"

#: ../duplicity/manifest.py:98
#, python-format
msgid ""
"Fatal Error: Backup source directory has changed.\n"
"Current directory: %s\n"
"Previous directory: %s"
msgstr ""
"Súlyos hiba: A biztonsági mentést kérő forráskönyvtár megváltozott.\n"
"Jelenlegi könyvtár: %s\n"
"Előző könyvtár: %s"

#: ../duplicity/manifest.py:107
msgid ""
"Aborting because you may have accidentally tried to backup two different "
"data sets to the same remote location, or using the same archive directory.  "
"If this is not a mistake, use the --allow-source-mismatch switch to avoid "
"seeing this message"
msgstr ""
"Leállok, mert lehet, hogy véletlenül megpróbáltál mentést készíteni két "
"különböző adatkészletről ugyanarra a távoli tárhelyre, vagy "
"archívumkönyvtárba. Ha nincs szó hibázásról, használd az --allow-source-"
"mismatch kapcsolót, és nem küldök ilyen figyelmeztetést."

#: ../duplicity/manifest.py:244
msgid "Manifests not equal because different volume numbers"
msgstr "A kimutatások nem egyformák, mert a kötegek száma különbözik"

#: ../duplicity/manifest.py:249
msgid "Manifests not equal because volume lists differ"
msgstr "A kimutatások nem egyformák, mert a kötegek listája különbözik"

#: ../duplicity/manifest.py:254
msgid "Manifests not equal because hosts or directories differ"
msgstr ""
"A kimutatások nem egyformák, mert a célrendszerek vagy célkönyvtárak "
"különböznek"

#: ../duplicity/manifest.py:401
msgid "Warning, found extra Volume identifier"
msgstr "Figyelem, ráadás Kötegazonosítót találtam"

#: ../duplicity/manifest.py:427
msgid "Other is not VolumeInfo"
msgstr "A másik nem Köteginfo"

#: ../duplicity/manifest.py:430
msgid "Volume numbers don't match"
msgstr "A kötegszámok nem egyeznek"

#: ../duplicity/manifest.py:433
msgid "start_indicies don't match"
msgstr "A start_mutatószámok nem egyeznek"

#: ../duplicity/manifest.py:436
msgid "end_index don't match"
msgstr "A vég_mutatószám nem egyezik"

#: ../duplicity/manifest.py:443
msgid "Hashes don't match"
msgstr "A hash-ek nem egyeznek"

#: ../duplicity/path.py:109
#, python-format
msgid "Warning: %s invalid devnums (0x%X), treating as (0, 0)."
msgstr ""

#: ../duplicity/path.py:236 ../duplicity/path.py:295
#, python-format
msgid "Warning: %s has negative mtime, treating as 0."
msgstr "Figyelem: %s negatív m_idővel rendelkezik, 0-nak értelmezem."

#: ../duplicity/path.py:359
msgid "Difference found:"
msgstr "Találtam különbséget:"

#: ../duplicity/path.py:368
#, python-format
msgid "New file %s"
msgstr "Új állomány: %s"

#: ../duplicity/path.py:371
#, python-format
msgid "File %s is missing"
msgstr "%s állomány hiányzik"

#: ../duplicity/path.py:374
#, python-format
msgid "File %%s has type %s, expected %s"
msgstr "A %%s állomány típusa %s, nekem %s kell"

#: ../duplicity/path.py:380 ../duplicity/path.py:406
#, python-format
msgid "File %%s has permissions %s, expected %s"
msgstr "A %%s állomány engedélyei: %s, nekem %s kell"

#: ../duplicity/path.py:385
#, python-format
msgid "File %%s has mtime %s, expected %s"
msgstr "A %%s állomány m_ideje %s, nekem %s kell"

#: ../duplicity/path.py:393
#, python-format
msgid "Data for file %s is different"
msgstr "A %s állománynak szánt adat kölönböző"

#: ../duplicity/path.py:401
#, python-format
msgid "Symlink %%s points to %s, expected %s"
msgstr "Szimbólikus link %%s ide mutat: %s, nekem %s kell"

#: ../duplicity/path.py:410
#, python-format
msgid "Device file %%s has numbers %s, expected %s"
msgstr "Eszközállomány %%s számai %s, nekem %s kell"

#: ../duplicity/path.py:572
#, python-format
msgid "Making directory %s"
msgstr "Könyvtár létrehozása: %s"

#: ../duplicity/path.py:582
#, python-format
msgid "Deleting %s"
msgstr "Törlés: %s"

#: ../duplicity/path.py:591
#, python-format
msgid "Touching %s"
msgstr "%s megérintése (touch)"

#: ../duplicity/path.py:598
#, python-format
msgid "Deleting tree %s"
msgstr "Fa törlése: %s"

#: ../duplicity/gpginterface.py:237
msgid "Threading not available -- zombie processes may appear"
msgstr ""

#: ../duplicity/gpginterface.py:701
#, python-format
msgid "GPG process %d terminated before wait()"
msgstr ""

#: ../duplicity/dup_time.py:52
#, python-format
msgid ""
"Bad interval string \"%s\"\n"
"\n"
"Intervals are specified like 2Y (2 years) or 2h30m (2.5 hours).  The\n"
"allowed special characters are s, m, h, D, W, M, and Y.  See the man\n"
"page for more information."
msgstr ""
"Rossz intervallum szöveg \"%s\"\n"
"\n"
"Az intervallumok ilyenek: 2Y (2 év) vagy 2h30m (2.5 óra).\n"
"A megengedett speciális karakterek: s, m, h, D, W, M, és Y.\n"
"Olvass utána a \"man\" oldalon."

#: ../duplicity/dup_time.py:58
#, python-format
msgid ""
"Bad time string \"%s\"\n"
"\n"
"The acceptible time strings are intervals (like \"3D64s\"), w3-datetime\n"
"strings, like \"2002-04-26T04:22:01-07:00\" (strings like\n"
"\"2002-04-26T04:22:01\" are also acceptable - duplicity will use the\n"
"current time zone), or ordinary dates like 2/4/1997 or 2001-04-23\n"
"(various combinations are acceptable, but the month always precedes\n"
"the day)."
msgstr ""
"Rosszul adtad meg az időt: \"%s\"\n"
"\n"
"Elfogadom a következőket. Intervallumok (pl. \"3D64s\"), w3-időpecsét,\n"
"pl. \"2002-04-26T04:22:01-07:00\" (vagy \"2002-04-26T04:22:01\" - duplicity\n"
"az érvényes időzónát használja) vagy hétköznapi dátumok, mint 2/4/1997\n"
"vagy 2001-04-23 (kölönböző kombinációk lehetnek, de a hónap mindig\n"
"előzze meg a napot)."

#: ../duplicity/tempdir.py:132
#, python-format
msgid "Using temporary directory %s"
msgstr "Ideiglenes könyvtár: %s"

#: ../duplicity/tempdir.py:176
#, python-format
msgid "Registering (mktemp) temporary file %s"
msgstr "Ideiglenes állomány regisztrálása (mktemp): %s"

#: ../duplicity/tempdir.py:198
#, python-format
msgid "Registering (mkstemp) temporary file %s"
msgstr "Ideiglenes állomány regisztrálása (mkstemp): %s"

#: ../duplicity/tempdir.py:230
#, python-format
msgid "Forgetting temporary file %s"
msgstr "Ideiglenes állomány elfelejtése: %s"

#: ../duplicity/tempdir.py:233
#, python-format
msgid "Attempt to forget unknown tempfile %s - this is probably a bug."
msgstr ""
"Ismeretlen %s ideiglenes állomány felejtésére tett kísérlet - ez "
"valószínűleg egy hiba (bug)."

#: ../duplicity/tempdir.py:252
#, python-format
msgid "Removing still remembered temporary file %s"
msgstr "Ismert ideiglenes %s állomány törlése"

#: ../duplicity/tempdir.py:255
#, python-format
msgid "Cleanup of temporary file %s failed"
msgstr "A %s ideiglenes állomány törlése sikertelen volt"

#: ../duplicity/tempdir.py:260
#, python-format
msgid "Cleanup of temporary directory %s failed - this is probably a bug."
msgstr ""
"A %s ideiglenes állomány törlése sikertelen volt - ez valószínűleg egy hiba "
"(bug)."

#: ../duplicity/util.py:99
#, python-format
msgid "IGNORED_ERROR: Warning: ignoring error as requested: %s: %s"
msgstr ""
"IGNORED_ERROR: Figyelem: a hibát figyelmen kívül hagyom, ahogy kérted: %s: %s"

#: ../duplicity/util.py:165
#, python-format
msgid "Releasing lockfile %s"
msgstr ""

#~ msgid "Found old backup set at the following time:"
#~ msgid_plural "Found old backup sets at the following times:"
#~ msgstr[0] "Következő idő szerinti régi biztonsági mentés készletet találtam:"
#~ msgstr[1] ""
#~ "Következő idők szerinti régi biztonsági mentés készleteket találtam:"

#~ msgid "Deleting backup set at time:"
#~ msgid_plural "Deleting backup sets at times:"
#~ msgstr[0] "Következő idő szerinti biztonsági mentés készlet törlése:"
#~ msgstr[1] "Következő idők szerinti biztonsági mentés készletek törlése:"

#~ msgid "Unable to load gio module"
#~ msgstr "Nem tudtam betölteni a gio modult"

#, python-format
#~ msgid ""
#~ "One only volume required.\n"
#~ "Renaming %s to %s"
#~ msgstr ""
#~ "Csak egy kötegre van szükség.\n"
#~ "Átnevezem ezt: %s erre: %s"

#, python-format
#~ msgid "Starting to write %s"
#~ msgstr "Elkezdem írni: %s"

#, python-format
#~ msgid "File %s not found locally after get from backend"
#~ msgstr ""
#~ "A(z) %s fájl nem található helyileg a háttérprogramból való lekérés után"
